spring:
  application:
    name: spring-cloud-nacos-discovery-client



  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ## 指定命令空间
        namespace: d033967d-013d-4f01-9d23-8326105615ac
server:
  port: 12000
